
### 1 pod with nginx  and 1 Service creation (NODE PORT SERVICE)

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
   server: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    server: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


### this will crete 1 pod and 1 node port service @ 19 MIN
# kubectl apply -f 02-service.yaml
# kubectl get service 
# WHEN WE CREATE NODE PORT BY DEFAULT CLUSTER IP WILL CREATED 
# kubectl get service -o wide
# kubectl get pods
# you wi;ll get the ip of pod and node (pvt ip) 
# try to access the nodes in the internet using the public ip of those .... the magic is YOU WILL ACCESS THE NGINX SERVER FROM THE TWO NODES WHICH HAVE BEEN CREATED.